spring.application.name=api-gateway
server.port=8000
spring.output.ansi.enabled=always
eureka.client.service-url.defaultZone=${EUREKA_URL}


logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE



# Product Service Configuration for API Gateway
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**


# --- Order Service Route ---
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**
# spring.cloud.gateway.routes[1].filters[0]=TokenRelay

# --- Inventory Service Route ---
spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=lb://inventory-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory/**

# 1. Discovery Server Dashboard UI
spring.cloud.gateway.routes[3].id=discovery-server-gui
spring.cloud.gateway.routes[3].uri=http://localhost:8761
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[3].filters[0]=SetPath=/

# 2. Discovery Server Static Resources & API
spring.cloud.gateway.routes[4].id=discovery-server-static
spring.cloud.gateway.routes[4].uri=http://localhost:8761
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.security.oauth2.client.registration.keycloak.client-id=spring-cloud-client

spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.provider=keycloak


# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservice-realm
# spring.security.oauth2.client.registration.keycloak.client-secret=x7jqZ6LDM318TxFvUVTQ3239I7PpZXEF

# spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8181/realms/spring-microservice-realm



spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
# Log ထဲမှာ [ServiceName, TraceId, SpanId] ပေါ်အောင် လုပ်တာ
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]