spring.application.name=product-service
spring.data.mongodb.uri=${PRODUCT_DB_URI}

server.port=8080
eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER}
spring.output.ansi.enabled=always
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
# Log ထဲမှာ [ServiceName, TraceId, SpanId] ပေါ်အောင် လုပ်တာ
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]