spring.application.name=inventory-service
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=${INVENTORY_DB_URL}
spring.datasource.username=${INVENTORY_DB_USER}
spring.datasource.password=${INVENTORY_DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=4000
spring.output.ansi.enabled=always

eureka.client.service-url.defaultZone=${EUREKA_URL}
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]