spring.application.name=notification-service
server.port=8080

# Kafka Consumer
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.consumer.group-id=notification-group

# Eureka
eureka.client.service-url.defaultZone=http://eureka:password@discovery-server:8761/eureka