name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build api-gateway
      run: mvn -B package --file api-gateway/pom.xml -DskipTests
      
    - name: Build discovery-server
      run: mvn -B package --file discovery-server/pom.xml -DskipTests
      
    - name: Build inventory-service
      run: mvn -B package --file inventory-service/pom.xml -DskipTests
      
    - name: Build notification-service
      run: mvn -B package --file notification_service/pom.xml -DskipTests
      
    - name: Build order-service
      run: mvn -B package --file order-service/pom.xml -DskipTests
      
    - name: Build product-service
      run: mvn -B package --file product-service/pom.xml -DskipTests
      
    - name: Build Main-POM.XML
      run: mvn -B package --file pom.xml -DskipTests
      
